services:
  app:
    image: node
    command: sleep infinity
    working_dir: /var/www
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 8080
      SERVER: http://localhost:8081
    ports:
      - 8080:8080
    volumes:
      - ./app:/var/www
  server:
    image: node
    command: sleep infinity
    working_dir: /var/www
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 8081
    ports:
      - 8081:8081
    volumes:
      - ./server:/var/www